export type Theme = {
  id: string;
  name: string;
  fontTitle: string;
  fontBody: string;
  bgClass: string;
  textClass: string;
  accentClass: string;
  buttonClass: string;
  quote: string;
};

export const THEMES: Theme[] = [
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    fontTitle: 'font-["Space_Grotesk"] uppercase tracking-tighter',
    fontBody: 'font-["Space_Grotesk"]',
    bgClass: 'bg-gradient-to-br from-purple-900 via-black to-cyan-900 border-cyan-500/30',
    textClass: 'text-cyan-400 drop-shadow-[0_0_8px_rgba(34,211,238,0.8)]',
    accentClass: 'bg-pink-500 shadow-[0_0_15px_rgba(236,72,153,0.5)]',
    buttonClass: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/50 hover:bg-cyan-500/40',
    quote: '"Wake the f*** up, samurai. We have a challenge to burn."',
  },
  {
    id: 'cottagecore',
    name: 'Cottagecore',
    fontTitle: 'font-["Playfair_Display"] italic',
    fontBody: 'font-["Inter"]',
    bgClass: 'bg-[#f4f1ea] border-[#8b9a73]/30',
    textClass: 'text-[#4a5d23]',
    accentClass: 'bg-[#8b9a73]',
    buttonClass: 'bg-[#8b9a73]/20 text-[#4a5d23] border-[#8b9a73]/50 hover:bg-[#8b9a73]/40',
    quote: '"Nature does not hurry, yet everything is accomplished."',
  },
  {
    id: 'gymbro',
    name: 'Gym Bro',
    fontTitle: 'font-["Anton"] uppercase tracking-wide',
    fontBody: 'font-["Inter"] font-bold',
    bgClass: 'bg-zinc-900 border-red-600/30',
    textClass: 'text-red-500',
    accentClass: 'bg-red-600',
    buttonClass: 'bg-red-600/20 text-red-500 border-red-600/50 hover:bg-red-600/40',
    quote: '"Push yourself because no one else is going to do it for you."',
  },
  {
    id: 'darkacademia',
    name: 'Dark Academia',
    fontTitle: 'font-["Playfair_Display"] tracking-widest',
    fontBody: 'font-["Playfair_Display"]',
    bgClass: 'bg-[#2c241b] border-[#d4af37]/30',
    textClass: 'text-[#d4af37]',
    accentClass: 'bg-[#8b0000]',
    buttonClass: 'bg-[#d4af37]/20 text-[#d4af37] border-[#d4af37]/50 hover:bg-[#d4af37]/40',
    quote: '"Knowledge is power, but discipline is the key to the library."',
  },
  {
    id: 'anime',
    name: 'Anime',
    fontTitle: 'font-["Bangers"] tracking-wider',
    fontBody: 'font-["Inter"] font-bold',
    bgClass: 'bg-gradient-to-tr from-orange-500 to-yellow-400 border-white/50',
    textClass: 'text-white drop-shadow-[2px_2px_0_rgba(0,0,0,1)]',
    accentClass: 'bg-white',
    buttonClass: 'bg-white/20 text-white border-white/50 hover:bg-white/40',
    quote: '"Believe it! Your ninja way starts today."',
  },
  {
    id: 'y2k',
    name: 'Y2K',
    fontTitle: 'font-["Space_Grotesk"] font-black italic tracking-tighter',
    fontBody: 'font-["Inter"]',
    bgClass: 'bg-gradient-to-r from-fuchsia-500 to-blue-500 border-white/40',
    textClass: 'text-white drop-shadow-md',
    accentClass: 'bg-yellow-400',
    buttonClass: 'bg-white/20 text-white border-white/50 hover:bg-white/40',
    quote: '"That\'s hot. Keep it 100 for the next 30 days."',
  },
  {
    id: 'stoic',
    name: 'Stoic',
    fontTitle: 'font-["Cinzel"] tracking-widest',
    fontBody: 'font-["Inter"]',
    bgClass: 'bg-zinc-950 border-zinc-800',
    textClass: 'text-zinc-300',
    accentClass: 'bg-zinc-100',
    buttonClass: 'bg-zinc-800 text-zinc-300 border-zinc-700 hover:bg-zinc-700',
    quote: '"We suffer more often in imagination than in reality."',
  },
  {
    id: 'meme',
    name: 'Meme',
    fontTitle: 'font-["Anton"] uppercase tracking-tight',
    fontBody: 'font-["Inter"] font-black uppercase',
    bgClass: 'bg-white border-black',
    textClass: 'text-black',
    accentClass: 'bg-yellow-400',
    buttonClass: 'bg-black/5 text-black border-black/20 hover:bg-black/10',
    quote: '"Much challenge. Very discipline. Wow."',
  },
  {
    id: 'luxury',
    name: 'Luxury',
    fontTitle: 'font-["Playfair_Display"] font-light tracking-[0.2em] uppercase',
    fontBody: 'font-["Inter"] font-light',
    bgClass: 'bg-black border-zinc-800',
    textClass: 'text-zinc-100',
    accentClass: 'bg-zinc-100',
    buttonClass: 'bg-zinc-900 text-zinc-100 border-zinc-800 hover:bg-zinc-800',
    quote: '"Excellence is not an act, but a habit."',
  },
  {
    id: 'nature',
    name: 'Nature',
    fontTitle: 'font-["Inter"] font-bold tracking-tight',
    fontBody: 'font-["Inter"]',
    bgClass: 'bg-emerald-950 border-emerald-800/50',
    textClass: 'text-emerald-100',
    accentClass: 'bg-emerald-500',
    buttonClass: 'bg-emerald-900/50 text-emerald-100 border-emerald-800 hover:bg-emerald-800/50',
    quote: '"Look deep into nature, and then you will understand everything better."',
  },
  {
    id: 'retro90s',
    name: 'Retro 90s',
    fontTitle: 'font-["Bungee"]',
    fontBody: 'font-["Inter"] font-bold',
    bgClass: 'bg-teal-400 border-4 border-black',
    textClass: 'text-black',
    accentClass: 'bg-pink-500',
    buttonClass: 'bg-yellow-400 text-black border-2 border-black hover:bg-yellow-300 shadow-[4px_4px_0_0_rgba(0,0,0,1)]',
    quote: '"Radical! Take it to the max, dude."',
  },
  {
    id: 'minimal',
    name: 'Minimal',
    fontTitle: 'font-["Inter"] font-black tracking-tighter',
    fontBody: 'font-["Inter"]',
    bgClass: 'bg-zinc-100 border-zinc-200',
    textClass: 'text-zinc-900',
    accentClass: 'bg-black',
    buttonClass: 'bg-white text-zinc-900 border-zinc-200 hover:bg-zinc-50',
    quote: '"Less, but better."',
  },
  {
    id: 'vaporwave',
    name: 'Vaporwave',
    fontTitle: 'font-["Space_Grotesk"] uppercase tracking-[0.3em]',
    fontBody: 'font-["Inter"] font-light',
    bgClass: 'bg-gradient-to-br from-[#ff71ce] via-[#01cdfe] to-[#05ffa1] border-white/30',
    textClass: 'text-white drop-shadow-[2px_2px_0_rgba(185,103,255,0.8)]',
    accentClass: 'bg-[#b967ff]',
    buttonClass: 'bg-white/20 text-white border-white/50 hover:bg-white/40',
    quote: '"I t \' s   a l l   i n   y o u r   h e a d ."',
  },
];
